AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda Hello World
Resources:
  i8labsbackendbond:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CD HelloWorld'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::093833860903:role/BondAPI_Lambda'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getHelloWorldTest
            Method: get
      Environment:
        Variables:
          REGION: ap-south-1