AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Hello World
Resources:
  i8labsbackendbond:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CD HelloWorld'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::679381524914:role/BondAPI_Lambda'
      Layers:
        - arn:aws:lambda:ap-south-1:679381524914:layer:i8labs-bond-pymySQL:1
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getHelloWorldTest
            Method: get
      Environment:
        Variables:
          REGION: ap-south-1